# Generated by Django 4.0.1 on 2022-02-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_myvar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myvar',
        ),
    ]
