# Generated by Django 4.0.1 on 2022-02-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
