# Generated by Django 4.0.1 on 2022-02-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cati',
        ),
    ]
